version:  '3'

services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webroot:/var/www/html
    environment:
      ALLOW_OVERRIDE: 'true'
    links:
      - mysql
      - neo4j

  mysql:
    image: mariadb:10.1
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "custom-root-pw"
      MYSQL_USER: "sf-db-user"
      MYSQL_PASSWORD: "sf-usr-pw"
      MYSQL_DATABASE: "sf-db"
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
      - 4433:443
    restart: always
    environment:
      MYSQL_USERNAME: "sf-db-user"
      MYSQL_PASSWORD: "sf-usr-pw"
    external_links:
      - mysql:db

  neo4j:
    image: neo4j:2.3
    network_mode: bridge
    ports: 
      - 7474:7474
    volumes: 
      - ./neo4j/conf:/conf
      - ./neo4j/import:/import
      - ./neo4j/data:/data
    ulimits:
      nofile: 
        soft: 20000
        hard: 40000
    environment:
      NEO4J_AUTH: "neo4j/sf-graph-pw"
      NEO4J_CACHE_MEMORY: "4G"